name = "NBPMscape"
uuid = "db6c8c85-0f38-4083-b9e9-69418a0b7188"
version = "0.1.4"
authors = ["Erik Volz <erik.volz@gmail.com>", "Kieran O. Drake"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CMPlot = "79866cb8-e9c7-11e9-0ec0-4bf12ba13504"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerAnalyses = "fee4b835-1841-44f8-82ea-42813857171a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
AlgebraOfGraphics = "0.11.8"
CMPlot = "1.0.2"
CSV = "0.10"
CairoMakie = "0.15.6"
CategoricalArrays = "0.10.8"
DataFrames = "1.7"
DataFramesMeta = "0.15.5"
Dates = "1.11.0"
Debugger = "0.7"
DifferentialEquations = "7"
Distributions = "0.25"
ForwardDiff = "1.3.0"
GLM = "1.9.0"
HypothesisTests = "0.11.6"
Interpolations = "0.15"
JLD2 = "0.6.2"
JumpProcesses = "9"
KernelDensity = "0.6.9"
LinearAlgebra = "1"
NamedArrays = "0.10.4"
Optim = "1.13.2"
PlotlyJS = "0.18.15"
Plots = "1.40"
PowerAnalyses = "0.2.7"
QuadGK = "2.11.2"
RData = "1"
Random = "1"
Revise = "3"
SpecialFunctions = "2"
Statistics = "1.11.1"
StatsBase = "0.34"
StatsPlots = "0.15.7"
Suppressor = "0.2.8"
Test = "1"
UUIDs = "1"
XLSX = "0.10.4"
YAML = "0.4.16"
